version: '3'
services:

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_PASSWORD=donotusethisinprod

  app:
    build: ../
    depends_on:
      - "db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=donotusethisinprod
    ports:
      - "80:8080"
