name: Integrations tests (Python)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch docker-compose up
        run: |
          cd integration-tests
          docker-compose up -d
      - name: Wait to be online
        run: |
          python3 integration-tests/waitToBeOnline.py
      - name: Integration tests
        run: |
          python3 integration-tests/launchIntegrationTests.py
